// <auto-generated />
namespace DisasterPOEApp.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class DisasterPOEApp : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(DisasterPOEApp));
        
        string IMigrationMetadata.Id
        {
            get { return "202309211242411_DisasterPOEApp"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
